development:
  adapter: postgresql
  encoding: unicode
  database: banking_development
  pool: 5
  username: banking
  password: 

test:
  adapter: postgresql
  encoding: unicode
  database: banking_test
  pool: 5
  username: banking
  password: 